config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations:      'users/registrations',
                                    omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'galleries#index'

  namespace :admin_panel do
    resources :users, only: :index
  end

  resources :galleries
  resources :images
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gallery.rb
class Gallery < ApplicationRecord
  mount_uploader :cover_image,  ImageUploader

  has_and_belongs_to_many :images
  belongs_to :user

  validates :title, presence: true
end

app/models/image.rb
class Image < ApplicationRecord
  scope :with_selected_tags, ImagesWithSelectedTagsQuery

  mount_uploader :image_file,  ImageUploader

  has_and_belongs_to_many :galleries

  has_many :image_tags, dependent: :destroy
  has_many :tags, through: :image_tags

  belongs_to :user

  validates :image_file, presence: true
end

app/models/image_tag.rb
class ImageTag < ApplicationRecord
  belongs_to :image
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :image_tags
  has_many :images, through: :image_tags

  validates :name, presence: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:google_oauth2]

  has_many :galleries
  has_many :images

  validates :first_name, :last_name, presence: true

  mount_uploader :avatar, ImageUploader

  def self.from_omniauth(access_token)
    data = access_token.info
    user = User.where(email: data['email']).first

    user ||= User.create(
        remote_avatar_url: data['image'],
        first_name: data['first_name'],
        last_name: data['last_name'],
        email: data['email'],
        password: Devise.friendly_token[0, 20])
    user
  end
end

app/controllers/admin_panel/users_controller.rb
module AdminPanel
  class UsersController < ApplicationController
    def index
      authorize User
      @users = User.all
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    flash[:danger] = 'You are not authorized to perform this action.'
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  def index
    @galleries = current_user.galleries
  end

  def new
    @gallery = Gallery.new
  end

  def create
    @gallery = Gallery.new(gallery_params)

    if @gallery.save
      redirect_to galleries_path, notice: t('galleries.created')
    else
      render :new
    end
  end

  def gallery_params
    params.require(:gallery).permit(:cover_image, :title, :description).merge(user: current_user)
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def index
    @filters = ImagesFiltersForm.new(tags: tags)
    @images  = current_user.images.with_selected_tags(tags: tags)
  end

  def new
    @upload_form = UploadForm.new(images: []).as(current_user)
    @galleries   = current_user.galleries
  end

  def create
    @upload_form = UploadForm.new(upload_params).as(current_user)

    if @upload_form.save
      redirect_to images_path, notice: "The image has been uploaded."
    else
      @galleries    = current_user.galleries
      flash[:error] = t('images.errors.upload_failed')
      render :new
    end
  end

  private

  def upload_params
    params.require(:upload)
  end

  def tags
    params.dig(:images_filters, :tags)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    @user = User.from_omniauth(request.env['omniauth.auth'])

    if @user.persisted?
      flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
      sign_in_and_redirect @user, event: :authentication
    else
      session['devise.google_data'] = request.env['omniauth.auth'].except(:extra)
      redirect_to new_user_registration_url, alert: @user.errors.full_messages.join("\n")
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name])
  end

  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: %i[first_name last_name avatar])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_name(user = nil)
    user.first_name.to_s + ' ' + user.last_name.to_s
  end

  def oauth_provider_name(provider)
    case provider
    when :google_oauth2
      'Google'
    else
      OmniAuth::Utils.camelize(provider)
    end
  end
end

app/helpers/flashes_helper.rb
module FlashesHelper
  def bootstrap_class_for(flash_type)
    case flash_type.to_sym
    when :success
      'alert-success'
    when :error
      'alert-danger'
    when :alert
      'alert-warning'
    when :notice
      'alert-info'
    else
      flash_type.to_s
    end
  end
end

app/views/admin_panel/users/index.html.erb
<table class="table">
  <thead>
  <tr>
    <th scope="col">#</th>
    <th scope="col">First Name</th>
    <th scope="col">Last Name</th>
    <th scope="col">Email</th>
    <th scope="col">Admin</th>
  </tr>
  </thead>
  <tbody>
  <% @users.each_with_index do |user, index| %>
    <tr>
      <th scope="row"><%= index + 1 %></th>
      <td><%= user.first_name %></td>
      <td><%= user.last_name %></td>
      <td><%= user.email %></td>
      <td><%= user.admin %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/galleries/index.html.erb
<br>
<div class="container">
  <%= link_to 'Add new gallery', new_gallery_path, class: 'btn btn-success btn-lg btn-block' %>
</div>
<br>
<div class="gallery-list inner-body">
  <div class="container">

    <% @galleries.each do |gallery| %>
      <div class="cardList">
        <% gallery.images.first(3).each do |image| %>
          <div class="card">
            <div class="card__bg" style="background-image: url('<%= image.image_file.url(:thumb) %>')"></div>
          </div>
        <% end %>

        <% if gallery.images.count == 0 && gallery.cover_image.blank? %>
          <div class="card">
            <div class="card__bg" style="background: grey;')"></div>
          </div>
        <% end %>

        <% if gallery.cover_image.present? %>
          <div class="card">
            <div class="card__bg" style="background-image: url('<%= gallery.cover_image.url(:thumb) %>')"></div>
          </div>
        <% end %>

        <span class="cardList__title"><%= gallery.title %></span>
      </div>
    <% end %>
  </div>
</div>

app/views/galleries/new.html.erb
<div class="container">
  <br>
  <h1>Create gallery</h1>
  <br>
  <%= simple_form_for(@gallery, wrapper: :vertical_form) do |f| %>
    <%= f.input :cover_image, as: :file %>
    <%= f.input :title %>
    <%= f.input :description %>
    <br>
    <%= f.button :submit, 'Create gallery' %>
  <% end %>
  <br>
</div>

app/views/images/index.html.erb
<br>
<%= simple_form_for(@filters, url: images_path(@filters), html: { method: :get }, wrapper: :vertical_form) do |f| %>
  <%= f.input :tags, as: :select, collection: Tag.all, value_method: :name, input_html: { multiple: true, class: 'autocomplete-search-tags' } %>
  <br>
  <%= f.button :submit, 'Find images' %>
<% end %>
<br>
<div id="lightgallery">
  <% @images.each do |image| %>
      <%= link_to image_tag(image.image_file.url(:thumb)), image.image_file.url %>
    <% end %>
</div>
<br>

app/views/images/new.html.erb
<div class="container">
  <br>
  <h1>Upload images</h1>
  <br>
  <%= simple_form_for(@upload_form, url: images_path(@images), html: { method: :post }, wrapper: :vertical_form) do |f| %>
    <%= f.input :images, as: :file, input_html: { multiple: true } %>
    <%= f.input :galleries_ids, as: :select, collection: @galleries, input_html: { multiple: true } %>
    <%= f.input :tags, as: :select, collection: Tag.all, value_method: :name, input_html: { multiple: true, class: 'autocomplete-add-tags' } %>
    <br>
    <%= f.button :submit, 'Send images' %>
  <% end %>
  <br>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EpicGallery</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_pack_tag "application", "data-turbolinks-track": "reload", media: "all" %>
  <%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>
</head>

<body>

<nav class="navbar navbar-expand-md navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Epic Gallery</a>

  <button class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbarNav"
          aria-controls="navbarNav"
          aria-expanded="false"
          aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav mr-auto">
      <% if current_user %>
        <li class="nav-item">
          <%= link_to 'Galleries', galleries_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Images', images_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Upload images', new_image_path, class: 'nav-link' %>
        </li>
      <% end %>

      <% if current_user && current_user.admin? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Admin Tools
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to 'Users list', admin_panel_users_path, class: 'dropdown-item' %>
          </div>
        </li>
      <% end %>
    </ul>

    <ul class="navbar-nav ml-auto">
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="userDropDown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Hello, <%= full_name(current_user) %>!
            <%= image_tag(current_user.avatar_url, class: 'profile-image') if current_user.avatar? %>
          </a>
          <div class="dropdown-menu" aria-labelledby="userDropDown">
            <%= link_to('Edit account', edit_user_registration_path, class: 'dropdown-item') %>
            <%= link_to('Log out', destroy_user_session_path, method: :delete, class: 'dropdown-item') %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Log in', new_user_session_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

<% flash.each do |type, message| %>
  <% unless message.to_s.strip == 'true' %>
    <div class="flash flash--notice alert <%= bootstrap_class_for(type) %>">
      <button class="btn btn--stripped close" data-dismiss="alert">×</button>
      <%= message.is_a?(Array) ? message.join("<br>").html_safe : message %>
    </div>
  <% end %>
<% end %>

<div class="container">
  <%= yield %>
</div>

<div class="alert alert-info">
  <%= debug(params) if Rails.env.development? %>
</div>

</body>
</html>